// This is where we specify our magic numbers to be used throughout the app.
/* eslint-disable @typescript-eslint/no-magic-numbers */

export const ONE_SECOND_IN_MILLISECONDS = 1000;
export const TWO_SECONDS_IN_MILLISECONDS = 2 * ONE_SECOND_IN_MILLISECONDS;
export const ONE_MINUTE_IN_SECONDS = 60;
export const ONE_HOUR_IN_SECONDS = 60 * ONE_MINUTE_IN_SECONDS;
export const ONE_DAY_IN_SECONDS = 24 * ONE_HOUR_IN_SECONDS;
export const ONE_WEEK_IN_SECONDS = 7 * ONE_DAY_IN_SECONDS;
export const THIRTY_DAYS_IN_SECONDS = 30 * ONE_DAY_IN_SECONDS;
export const ONE_YEAR_IN_SECONDS = 365 * ONE_DAY_IN_SECONDS;

export const ONE_MINUTE_IN_MILLISECONDS = 1000 * ONE_MINUTE_IN_SECONDS;
export const ONE_HOUR_IN_MILLISECONDS = 60 * ONE_MINUTE_IN_MILLISECONDS;
export const TWELVE_HOUR_IN_MILLISECONDS = 12 * ONE_HOUR_IN_MILLISECONDS;
export const ONE_DAY_IN_MILLISECONDS = 24 * ONE_HOUR_IN_MILLISECONDS;
export const ONE_WEEK_IN_MILLISECONDS = 7 * ONE_DAY_IN_MILLISECONDS;
export const ONE_YEAR_IN_MILLISECONDS = 365 * ONE_DAY_IN_MILLISECONDS;
export const THIRTY_DAYS_IN_MILLISECONDS = 30 * ONE_DAY_IN_MILLISECONDS;

export const MS_PER_S = ONE_SECOND_IN_MILLISECONDS;

export const SECONDS_PER_BLOCK = 13.3;
